### ISSUE TITLE
browse certificate store button not working in Linux

### ISSUE THREAD

**Issue by dkebler** [mlaily/KeePass-CertificateShortcutProvider#5] opened 2022-12-02 23:47 UTC
I want to try out your plugin.  I am running keepass (latest)  on linux mint (ubuntu 22.04).   Linux uses mono for .net 

I've made keys and cert and moved copy of the cert to the mono (i.e. windows) certificate store.
with a little bash script.  Was assuming for now I can use the cert in this way (later I'll set up access via NFC)

```
#!/bin/bash
len=${2:-4096}
echo  generate a self signed certificate $1.pem with length $len
if [[ ! -f "ca.pem.cer" ]]; then
    echo NO CA KEY ca.pem
    openssl genrsa -aes256 -out ca-key.pem $len
    echo create a CA
    openssl req -new -x509 -sha256 -days 100000 -key ca-key.pem -out ca.pem.cer 
    sudo certmgr -add -c -m CA ca.pem.cer 
fi
echo MAKE certifcate $1.pem.cer
openssl genrsa -out $1-key.pem $len
openssl req -new -sha256 -subj "/CN=kpcert" -key $1-key.pem -out $1.csr
openssl x509 -req -sha256 -days 10000 -in $1.csr -CAcreateserial  -CA ca.pem.cer -CAkey ca-key.pem -out $1.pem.cer 
sudo certmgr -add -c -m My $1.pem.cer 
```
All looks good but your button  `browse certificate store`` does nothing, does not open any dialog let alone list certs in my store

can you illuminate a bit more or provide assistance to get this working?

Maybe your code won't work with Linux (ubuntu?)  :(

https://github.com/mlaily/KeePass-CertificateShortcutProvider/blob/035f5c2a8755f6a01b82d36f82303c7df4e6fb80/CertificateShortcutProvider/KeyCreationForm.cs#L73

**Comment by dkebler** [comment] 2022-12-02 23:50
Hmm.   looks like there is a "mono" certificate store that I must use?

**Comment by dkebler** [comment] 2022-12-02 23:56
OK yes there is such a thing so added it
`certmgr -add -c -m Trust xxx.pem.cer` 
```
Mono Certificate Manager - version 6.12.0.122
Manage X.509 certificates and CRL from stores.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.
1 certificate(s) added to store Trust.
```
but alas the button still doesn't work :(

**Comment by mlaily** [comment] 2022-12-03 06:58
Hey sorry, I don't think it will work with mono.  
Looking at their code it seems they didn't implement the method I'm calling: https://github.com/mono/mono/blob/5d2e3bc3b3c8184d35b2f7801e88d96470d367c4/mcs/class/System.Security/System.Security.Cryptography.X509Certificates/X509Certificate2UI.cs#L89

The way to go to make it work on platforms other than Windows would be to use PKCS#11 to access the certificate, but the code would be a bit more complicated than it is right now, and it would likely make it more cumbersome to use this plugin on Windows.

I'm going to close this issue as a duplicate of #1.

**Closed as not planned by mlaily** 2022-12-03 06:58 UTC

**Comment by dkebler** [comment] 2022-12-03 15:45
If I generated the cspkey in a windows install do you think the rest of the key provider code would work (with mono)?

**Comment by dkebler** [comment] 2022-12-03 15:53
Also might want to say up front in your readme that it doesn't work with linux/mono (i.e. windows only) and point to these issues.

**Comment by mlaily** [comment] 2022-12-03 17:45
> If I generated the cspkey in a windows install do you think the rest of the key provider code would work (with mono)?

I don't think so: accessing the hardware token at decryption time is done through the [Windows Certificates Store abstraction](https://github.com/mlaily/KeePass-CertificateShortcutProvider/blob/master/CertificateShortcutProvider/CryptoHelpers.cs#L101) and I doubt it has been implemented on mono. I didn't check though!
